const genresTypes = {
  SELECT_GENRE: 'SELECT_GENRE',
  LOAD_GENRES_INIT: 'LOAD_GENRES_INIT',
  LOAD_GENRES_SUCCESS: 'LOAD_GENRES_SUCCESS',
  LOAD_GENRES_FAILURE: 'LOAD_GENRES_FAILURE',
}

export default genresTypes
