const genresTypes = {
  ADD_TO_GENRE_FILTER: 'ADD_TO_GENRE_FILTER',
  REMOVE_FROM_GENRE_FILTER: 'REMOVE_FROM_GENRE_FILTER',
  LOAD_GENRES_INIT: 'LOAD_GENRES_INIT',
  LOAD_GENRES_SUCCESS: 'LOAD_GENRES_SUCCESS',
  LOAD_GENRES_FAILURE: 'LOAD_GENRES_FAILURE',
}

export default genresTypes
