export default [
  {
    id: 'mid01',
    title: 'Movie Title',
    year: '1998',
    runtime: '128 min',
    director: 'Me',
    actors: 'Me and Someone Else',
    poster: 'http://www.url.com/picture.jpg',
    rating: 4,
    imdbID: 'tt001',
    genres: { genreId01: { name: 'Action' } },
    country: 'USA',
    language: 'ENG',
    plot: 'A story about something',
    production: 'Dogs Inc',
    ratings: [
      { Source: '', Value: '' },
      { Source: '', Value: '' },
      { Source: '', Value: '' },
    ],
    released: 'May 1st 1998',
    writer: 'Someone Else',
  },
  {
    id: 'mid02',
    title: 'Movie Title',
    year: '1998',
    runtime: '128 min',
    director: 'Me',
    actors: 'Me and Someone Else',
    poster: 'http://www.url.com/picture.jpg',
    rating: 4,
    imdbID: 'tt002',
    genres: { genreId01: { name: 'Action' } },
    country: 'USA',
    language: 'ENG',
    plot: 'A story about something',
    production: 'Dogs Inc',
    ratings: [
      { Source: '', Value: '' },
      { Source: '', Value: '' },
      { Source: '', Value: '' },
    ],
    released: 'May 1st 1998',
    writer: 'Someone Else',
  },
]
