const moviesTypes = {
  GET_ALL_MOVIES: 'GET_ALL_MOVIES',
  GET_ALL_MOVIES_SUCCESS: 'GET_ALL_MOVIES_SUCCESS',
  GET_ALL_MOVIES_FAILURE: 'GET_ALL_MOVIES_FAILURE',
  GET_LATEST_MOVIES: 'GET_LATEST_MOVIES',
  GET_LATEST_MOVIES_SUCCESS: 'GET_LATEST_MOVIES_SUCCESS',
  GET_LATEST_MOVIES_FAILURE: 'GET_LATEST_MOVIES_FAILURE',
  CREATE_MOVIE: 'CREATE_MOVIE',
  CREATE_MOVIE_SUCCESS: 'CREATE_MOVIE_SUCCESS',
  CREATE_MOVIE_FAILURE: 'CREATE_MOVIE_FAILURE',
  UPDATE_MOVIE: 'UPDATE_MOVIE',
  UPDATE_MOVIE_SUCCESS: 'UPDATE_MOVIE_SUCCESS',
  UPDATE_MOVIE_FAILURE: 'UPDATE_MOVIE_FAILURE',
  DELETE_MOVIE: 'DELETE_MOVIE',
  DELETE_MOVIE_SUCCESS: 'DELETE_MOVIE_SUCCESS',
  DELETE_MOVIE_FAILURE: 'DELETE_MOVIE_FAILURE',
}

export default moviesTypes
