const searchTypes = {
  SEARCH_FOR_MOVIE_TITLE: 'SEARCH_FOR_MOVIE_TITLE',
  SEARCH_FOR_MOVIE_TITLE_SUCCESS: 'SEARCH_FOR_MOVIE_TITLE_SUCCESS',
  SEARCH_FOR_MOVIE_TITLE_FAILURE: 'SEARCH_FOR_MOVIE_TITLE_FAILURE',
  SEARCH_FOR_MOVIE_ID: 'SEARCH_FOR_MOVIE_ID',
  SEARCH_FOR_MOVIE_ID_SUCCESS: 'SEARCH_FOR_MOVIE_ID_SUCCESS',
  SEARCH_FOR_MOVIE_ID_FAILURE: 'SEARCH_FOR_MOVIE_ID_FAILURE',
}

export default searchTypes
