const searchTypes = {
  SEARCH_FOR_MOVIE_TITLE: 'SEARCH_FOR_MOVIE_TITLE',
  SEARCH_FOR_MOVIE_TITLE_SUCCESS: 'SEARCH_FOR_MOVIE_TITLE_SUCCESS',
  SEARCH_FOR_MOVIE_TITLE_FAILURE: 'SEARCH_FOR_MOVIE_TITLE_FAILURE',
}

export default searchTypes